### ISSUE TITLE
filter not working at object root

### ISSUE THREAD

**Issue by undeflife** [bhmj/jsonslice#16]
input:`{"type":"click",name:"button"}`
expression: `$[?(@.type == "click")]`
expect output: `{"type":"click",name:"button"}`
actual output: `[]`

I'm  not sure this is a standard jsonpath  behavior but java's version  [jsonpath](https://github.com/json-path/JsonPath)  works as expect.

**Comment by bhmj** [comment]
Hello.

At the moment my implementation only supports filter expressions on _arrays_, as stated in README [here](https://github.com/bhmj/jsonslice#filters). I was mainly following Stefan Gössner's [article](https://goessner.net/articles/JsonPath/) on jsonpath, and it implies filters to be only applicable to arrays (no evidence of object filters whatsoever). 

Even though java's version of jsonpath supports this kind of expression, it looks like some kind of extension to the original proposal.

In your example you apply filter (an expression) to an object which is a root node, so the logic behind the expression seems to be like "return an object if the value of the field of an object is ...". Since there is only one object in the input, you could surpass the current restriction of _jsonslice_ by enclosing the whole input in square brackets like `[` + `{"type":"click",name:"button"}` + `]`. This way you'll get the expected output.

This is just a single discrepancy out of dozens, since there is no exact consensus on parsing the jsonpath, which you can see in [this](https://cburgmer.github.io/json-path-comparison/) awesome comparison chart by Christoph Burgmer.

**Comment by undeflife** [comment]
Alright though. 

I've had checked comparison you mentioned, this implementation of jsonpath meets the most of my need except this one , but i don't think modify input is reasonable. 

If you not planning to support this kind of extension i'll close this is issue.

Thanks for your work and explanation again.
