### ISSUE TITLE
NOT operator

### ISSUE THREAD

**Issue by edodekel** [bhmj/jsonslice#6]
can you support NOT operator? 
what i actually need is a filter to filter out several results based on the value in the fields using regxep:

for example:
[? NOT(@.name =~ /aaa.*/i || @.name =~ /bbb.*/i)]

the package is really useful.

**Comment by bhmj** [comment]
It looks a bit hard to implement this operator in the form you proposed since it will act like a function with a parameter which complicates parsing; but I could implement NOT EQUAL operator for regexps (`!=~`) so your example would look like [?( @.name !=~ /aaa./i && @.name !=~ /bbb./i )]

Will do it soon.

**Comment by edodekel** [comment]
perfect. thanks!

**Comment by bhmj** [comment]
"Not equal" operator for regexp `!=~` (or just `!~` for short) added.
So this expression works now: `[?( @.name !~ /aaa./i && @.name !~ /bbb./i )]`, and also it can be  shortened to `[?( @.name !~ /(aaa.)|(bbb.)/i )]`
